version: '3'
services:
  express:
    image: mongo-express:latest
    restart: always
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: demo
      ME_CONFIG_BASICAUTH_PASSWORD: demo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links: 
      - mongo
    networks:
      - mongonet

  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./storage:/data/db
    networks:
      - mongonet

networks:
  mongonet:
    driver: bridge
